= lrs

:logo: assets/logo.png

image::{logo}[logo,float="left"]

Welcome to the home of lrs, a new Rust standard library to power a new
generation of Linux-based devices. lrs is lightweight, fast, simple, free, and
provides the full safety of the Rust compiler.

== Acknowledgements

:musl_home: http://www.musl-libc.org/ 

Our gratitude goes to the {musl_home}[musl libc] developers who not only came up
with the excellent introduction you can read above but whose open-source library
also provides a clean documentation of the Linux kernel API.

== Features

test

== License

:mpl: https://www.mozilla.org/MPL/2.0/

The project is licensed under the {mpl}[MPL 2.0] license. Copyright belongs to
the individual contributors.

=== tl;dr

- Can be used in proprietary projects.
- Files can be mixed with files under other licenses.
- Changes to MPL licensed files must be published under the MPL.
- Code can freely be copied and used in GPL 2.0+, AGPL 3.0+, and LGPL 2.1+
  projects.

== Logo

:simple-linux-logo: http://dablim.deviantart.com/art/Simple-Linux-Logo-336131202
:dablim: http://dablim.deviantart.com/
:ccby: http://creativecommons.org/licenses/by-sa/4.0/

The link:{logo}[logo] shows a penguin in a sprocket.

It is based on {simple-linux-logo}[Simple Linux Logo] by {dablim}[Dablim] and is
licensed under {ccby}[CC BY-SA 4.0].
