= Cross compiling
ifdef::env-github[:outfilesuffix: .adoc]
include::../../VERSION.adoc[]
:toc: macro

This document explains how to cross-compile lrs-libc and lrs+musl programs.

toc::[]

== lrs-libc

Cross compiling lrs programs that don't depend on a libc is quite easy because
we don't have to cross-compile a libc.

=== Compiling lrs

Now we'll have to compile lrs for i686 and in the no_libc mode. To do this,
execute the lrs build system with the following command:

----
lb -t i686 -- --cfg no_libc
----

NOTE: Here we use the convention that `lb` is an alias for `lrs_build`.

We pass the `-t i686` argument to tell lrs_build to place the compiled crates in
the `obj/i686-unknown-linux-gnu` directory and to tell lrsc to compile for this
target. Then we pass `--cfg no_libc` directly to lrsc. This flag ensures that we
don't accidentally link against a libc later and that the compiled code contains
the necessary functions to work without a libc.

=== Installing `compiler-rt`

In order to build programs we'll have to download an additional dependency,
namely the `compiler-rt` library for our target. The `compiler-rt` version for
your system has already been installed with your rust distribution, but you
probably don't have the version for `i686` yet.

:dir: link:http://static.rust-lang.org/dist/{DATE}

The easiest way to get it is to extract it from a pre-built nightly. Go to
{dir}[] and download the correct `rust-std-nightly` archive. For `i686` it is
`rust-std-nightly-i686-unknown-linux-gnu.tar.gz`. Once you've extracted this
archive, look for the `libcompiler-rt.a` file which is in the innermost `lib`
directory. Where you have to copy it depends on where you've installed rustc.
For example, if

----
$ which rustc
/usr/local/bin/rustc
----

then you should copy the file into

----
/usr/local/lib/rustlib/i686-unknown-linux-gnu/lib
----

=== Compiling a program

Create a file `helloworld.rs` with the following content:

----
fn main() {
    println!("Hello World");
}
----

and compile it with the following command:


----
lrsc helloworld.rs -C link-args="-nostdlib -static" --target=i686-unknown-linux-gnu
----

`-nostdlib` tells the linker not to link certain glibc files. `-static` tells
it not to generate a dynamic executable.

DANGER: It's important to pass the `-static` flag. If you don't do this,
compiled programs will likely crash.

We can now execute the program and check that it's a 32 bit binary:

----
$ ./helloworld 
Hello World
$ file helloworld
helloworld: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, BuildID[sha1]=a683434e73a10a729023501e5e394238eaf638c4, not stripped
----

== lrs+musl

Cross compiling lrs+musl is a little bit more complicated because we also have
to cross-compile musl itself. This section assumes that you've already read the
<<using_musl# ,Using musl>> guide.

=== Building musl

To cross compile musl, we'll again use clang. Use the following `configure`
invocation:

----
CC=clang CFLAGS="--target=i686-unknown-linux-gnu" ./configure --disable-shared --target=i686
----

The last argument tells the musl build system to compile the i686-specific
files.

NOTE: For more exotic targets, such as arm, it is important that you pass the
`--disable-shared` argument. Otherwise the build system will invoke a linker at
some point and this linker will likely not be able to link arm objects.

Now you can build musl with `make`.

=== Building lrs

In order to build lrs, use the following command:

----
lb -r -t i686
----

This is almost the same as in the previous section, but this time we omit the
`--cfg no_libc` argument and add the `-r` flag. This flag tells lrs_build to
discard the previously compiled crates and to rebuild everything from scratch.
It is necessary to rebuild everything because an lrs compiled with the `no_libc`
flag cannot be used with musl.

=== Building a program

Now we can compile the helloworld program against musl:

----
lrsc helloworld.rs -C link-args="$HOME/c/musl/lib/crt1.o -nostdlib -static -L $HOME/c/musl/lib -lc -lpthread" --target=i686-unknown-linux-gnu
----

This is almost the same as in the <<using_musl# ,Using Musl>> tutorial but with
an additional `--target=i686-unknown-linux-gnu` argument.

----
$ ./helloworld 
Hello World
$ file helloworld
helloworld: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, BuildID[sha1]=6b39b12fd2acb0c82744211adc46021413b82685, not stripped
----

== Linking exotic targets with `ld.gold`.

In the previous examples we compiled for an i686 target. This worked nicely
because an x86_64 gcc can link i686 objects by default. If we were to go through
the steps above with an arm target, the very last step would fail because the
linker cannot link arm objects.

Let's assume that we've built musl and lrs for the arm target. When we now try
to compile our helloworld, we get the following output:

----
$ lrsc helloworld.rs -C link-args="$HOME/c/musl/lib/crt1.o -nostdlib -static -L $HOME/c/musl/lib -lc -lpthread" --target=arm-unknown-linux-gnueabi
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" [snip]
note: /usr/bin/ld: helloworld.0.o: Relocations in generic ELF (EM: 40)
[snip]
----

As you can see, lrsc invoked `/usr/bin/ld` which cannot link arm objects.
Instead, we have to convince gcc to use `/usr/bin/ld.gold` (which you might
have to install). To do this, use the following command

----
$ lrsc helloworld.rs -C link-args="-fuse-ld=gold $HOME/c/musl/lib/crt1.o -nostdlib -static -L $HOME/c/musl/lib -lc -lpthread" --target=arm-unknown-linux-gnueabi
----

The difference is that we've added `-fuse-ld=gold` to the `link-args` string.
Now we get new errors:

----
note: helloworld.0.o(.ARM.exidx.text._ZN4main20h8a1f0664cb65c8d0eaaE+0x0):
error: undefined reference to '__aeabi_unwind_cpp_pr0'
[snip]
----

The simplest way to fix this is to create dummy functions with these names that
don't do anything and add them to the linker invocation. Create a file
`arm_dummy.c` with the following content:

----
void __aeabi_unwind_cpp_pr0() { }
void __aeabi_unwind_cpp_pr1() { }
----

and compile it as follows:

----
$ clang --target=armv6-unknown-linux-gnueabi -c arm_dummy.c
----

Finally, let's invoke the linker again:

----
$ lrsc helloworld.rs -C link-args="-fuse-ld=gold arm_dummy.o
$HOME/c/musl/lib/crt1.o -nostdlib -static -L $HOME/c/musl/lib -lc -lpthread"
--target=arm-unknown-linux-gnueabi
----

Note the added `arm_dummy.o` argument. This time the compilation succeeds.

----
$ qemu-arm helloworld
Hello World
$ file helloworld
helloworld: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically
linked, BuildID[sha1]=2671b7ce5341028aa8649f2769947b77bf146ab6, not stripped
----

Here we used `qemu-arm` to run an arm program on x86_64.
